apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "collector.fullname" . }}
  labels:
    {{- include "collector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "collector.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "collector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args: ["--config","config.yaml"]
          volumeMounts:
          - name: config-volume
            mountPath: /config.yaml
            readOnly: true
            subPath: config.yaml
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value :=  .Values.env }}
            - name: {{ $key }}
              value: {{ tpl $value $ | quote }}
            {{- end }}
            - name: P_URL
              value: {{ .Values.parseable_server.url }}
            - name: P_USERNAME
              value: {{ .Values.parseable_server.username }}
            - name: P_PASSWORD
              value: {{ .Values.parseable_server.password }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "collector.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ if eq .Values.demo.app.create true }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.demo.app.name }}
  namespace: {{ .Values.demo.app.namespace }}
spec:
  selector:
    matchLabels:
      {{- with .Values.demo.app.labels }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
  replicas: 2
  template:
    metadata:
      labels:
      {{- with .Values.demo.app.labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: log-generator
        image: mingrammer/flog
        args: ["-f","json","-d","2s","-n","200","-l"]
        ports:
        - containerPort: 80 
{{ end }}