## on: [push, pull_request]
on: [pull_request]

name: Continuous integration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Fmt and Vet
      run: make fmt && make vet
